### PR TITLE
Change titus-repear into a oneshot unit

### PR DESCRIPTION
**Pull request by sargun**

### CODE REVIEW

**Review by alekar — APPROVED** [review]

**Comment by alekar** [comment]
Can we also get a metric published when we reap?

**Comment by sargun** [comment]
I ripped out metrics. Any reason you can't generate metrics from raven?

**Comment by alekar** [comment]
It seems pretty obvious what metrics we want and that we want them.
Besides, Raven can have a bad day?

**Comment by sargun** [comment]
@alekar the problem with counter metrics is that they happen so infrequently that often times it'll mis-report as 0, and you can't drill-down to nf.node

**Pull request merged**
