### PR TITLE
TITUS-6124: don't concurrently access pod annotations

### PR DESCRIPTION
**Pull request by tych0**
We have the following reports from titus-executor version
9f4c02f81575ec31915c3fb0be5ebfeaffec7e8c (with a bit of an ordering issue
in the stack trace because I am unsure how to sort kibana logs exactly):

...
started 1 container(s): [main], now monitoring for container status
Starting external logger
uploading using writer role
starting watchLoop
Processing msg from a container: '\x01' - main container is now running
Updating Task status
fatal error: concurrent map iteration and map write
Updated pod dir
goroutine 382 [running]:
runtime.throw({0x1222ead, 0xc000d17740})
	/usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc000d176e0 sp=0xc000d176b0 pc=0x433891
runtime.mapiternext(0x11f1d9c)
	/usr/local/go/src/runtime/map.go:858 +0x4eb fp=0xc000d17750 sp=0xc000d176e0 pc=0x40f8eb
github.com/Netflix/titus-executor/executor/runtime/docker.(*DockerRuntime).generatePlatformSidecarSpectatordMetrics(0xc000968380)
	/var/lib/buildkite-agent/builds/ip-192-168-1-90-1/netflix/titus-executor/executor/runtime/docker/docker.go:1598 +0x10e fp=0xc000d17a18 sp=0xc000d17750 pc=0xf3e8ae
github.com/Netflix/titus-executor/executor/runtime/docker.(*DockerRuntime).periodicallyReportTaskMetrics(0xc000968380, {0x145a290, 0xc000912000})
	/var/lib/buildkite-agent/builds/ip-192-168-1-90-1/netflix/titus-executor/executor/runtime/docker/docker.go:1505 +0x21d fp=0xc000d17fb8 sp=0xc000d17a18 pc=0xf3d2bd
github.com/Netflix/titus-executor/executor/runtime/docker.(*DockerRuntime).Start·dwrap·14()
	/var/lib/buildkite-agent/builds/ip-192-168-1-90-1/netflix/titus-executor/executor/runtime/docker/docker.go:1476 +0x2e fp=0xc000d17fe0 sp=0xc000d17fb8 pc=0xf3ce8e
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000d17fe8 sp=0xc000d17fe0 pc=0x463fc1
created by github.com/Netflix/titus-executor/executor/runtime/docker.(*DockerRuntime).Start
	/var/lib/buildkite-agent/builds/ip-192-168-1-90-1/netflix/titus-executor/executor/runtime/docker/docker.go:1476 +0x16b6
goroutine 1 [select]:
github.com/Netflix/titus-executor/vk/backend.(*Backend).RunWithOutputDir(0xc000a46000, {0x145a338, 0xc000311440}, {0x7ffc2d1ac6ee, 0x41})
	/var/lib/buildkite-agent/builds/ip-192-168-1-90-1/netflix/titus-executor/vk/backend/backend.go:246 +0x565
main.mainWithError({0x145a338, 0xc000311440}, 0xc000564480, 0xc0003b38c0, 0xc0003113e0, {0x145a488, 0xc0001b2108})
	/var/lib/buildkite-agent/builds/ip-192-168-1-90-1/netflix/titus-executor/cmd/titus-executor-backend/main.go:184 +0x14c5
main.main.func1(0xc00091a000)
	/var/lib/buildkite-agent/builds/ip-192-168-1-90-1/netflix/titus-executor/cmd/titus-executor-backend/main.go:103 +0x209
github.com/urfave/cli.HandleAction({0x101b100, 0xc000178870}, 0xc0002da540)
	/tmp/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0xa8
github.com/urfave/cli.(*App).Run(0xc0002da540, {0xc0001be000, 0x2, 0x2})
	/tmp/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:286 +0x625
main.main()
	/var/lib/buildkite-agent/builds/ip-192-168-1-90-1/netflix/titus-executor/cmd/titus-executor-backend/main.go:109 +0xc69
goroutine 18 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x0)
	/tmp/gopath/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:1181 +0x6a
created by k8s.io/klog/v2.init.0
	/tmp/gopath/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:420 +0xfb
goroutine 19 [select]:
github.com/Netflix/metrics-client-go/metrics.(*reporter).readLoop(0xc0001bac60, 0x0, 0x0)
	/tmp/gopath/pkg/mod/github.com/!netflix/metrics-client-go@v0.0.0-20171019173821-bb173f41fc07/metrics/reporter.go:150 +0x1ee
created by github.com/Netflix/metrics-client-go/metrics.WithURLInterval
	/tmp/gopath/pkg/mod/github.com/!netflix/metrics-client-go@v0.0.0-20171019173821-bb173f41fc07/metrics/reporter.go:70 +0x24f

this corresponds to an iteration over the pod annotations:

    for k, v := range r.c.Pod().Annotations

which it seems like we can concurrently modify in vk:

    // These annotations allow us to get data "back out" from the executor up to the control-plane, without having
    // to depend on the limitations of the PodStatus structure.
    b.podLock.Lock()
    defer b.podLock.Unlock()
    for k, v := range update.Details.NetworkConfiguration.ToAnnotationMap() {
	    b.pod.Annotations[k] = v
    }

Passing this lock around is a bit of a hack, but that seems (?) easier than
trying to fix whatever that comment is referencing, which I don't quite
understand.

Seems like this race has existed for a while, but has probably been more easily
triggerable since I added my log parsing code, which probably delays container
setup a few ms or something.

### CODE REVIEW

**Comment by solarkennedy** [comment]
Uh man, yuck.

What if instead this function:

```
func (c *PodContainer) Pod() *v1.Pod {
	return c.pod
}
```

Did all the locking for you?
That way every access to the `Pod()` function was tightly controlled and always sync'd?

**Comment by tych0** [comment]
I thought about that, you'd have to do it as:

```
func (c *PodContainer) Pod(criticalSection func(p *v1.Pod) error) error {
    p.podLock.Lock()
    defer p.podLock.Unlock()
    return criticalSection(p.pod)
}
```

so that people didn't keep the pointer around and access things anyway. That would still require changing a bunch (more?) call sites, but maybe it's cleaner in the long run. I'm happy to switch it to that if you like.

**Comment by tych0** [comment]
...and i guess they could keep the pointer by closing over some thing that they save it to, so maybe it's not worth all the effort. just put a big scary comment at the top of Pod() and hope for the best?

**Comment by tych0** [comment]
could also do it as,
```
func (c *PodContainer) Pod() (*v1.Pod, *sync.Mutex) {
    p.podLock.Lock()
    return p.pod, p.podLock
}
```

to make people think about it a bit more.

**Comment by solarkennedy** [comment]
> could also do it as,
> 
> ```
> func (c *PodContainer) Pod() (*v1.Pod, *sync.Mutex) {
>     p.podLock.Lock()
>     return p.pod, p.podLock
> }
> ```
> 
> to make people think about it a bit more.

I think that is a decent compromise. 
Some things are just read only, some rw, but all need to deal with the fact that pointers change. (right?)

**Comment by joshi-keyur** [comment]
> 

What is callers forget to Unlock the podLock before returning!

**Comment by tych0** [comment]
>  Some things are just read only, some rw, but all need to deal with the fact that pointers change. (right?)

It's really just callers modifying Annotation, for which there is one; but of course we have no way to tell what people are going to do with `*v1.Pod` when they ask for it :(

> What is callers forget to Unlock the podLock before returning!

I guess they can defer, so they hopefully won't forget? But yeah, sadness.

**Comment by solarkennedy** [comment]
> > Some things are just read only, some rw, but all need to deal with the fact that pointers change. (right?)
> 
> It's really just callers reading/modifying Annotation; but of course we have no way to tell what people are going to do with `*
v1.Pod` when they ask for it :(

I know there is one that modifies pod.status too
> 
> > What is callers forget to Unlock the podLock before returning!
> 
> I guess they can defer, so they hopefully won't forget? But yeah, sadness.

**Comment by tych0** [comment]
Ok, I rearranged things so that `.Pod()` returns the lock too. This is a bit of a painful change, but is maybe less-ugly than the previous change? In the process I was able to delete some stuff, I kept those as separate patches so we can land those independent of whichever approach we end up with here.

**Review by solarkennedy — APPROVED** [review]

**Pull request merged**
