### PR TITLE
Upgrade to Go 1.16

### PR DESCRIPTION
**Pull request by sargun**

### CODE REVIEW

**Comment by solarkennedy** [comment]
Hmm, I remember doing this before to go 1.15 and you linked me to a blog post about something....
What was it......

**Comment by sargun** [comment]
The syscall preemption messiness.

Sent from my iPhone

On Sep 29, 2021, at 15:35, Kyle Anderson ***@***.***> wrote:

﻿

Hmm, I remember doing this before to go 1.15 and you linked me to a blog
post about something....
What was it......

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Netflix/titus-executor/pull/740#issuecomment-930595025>,
or unsubscribe

**Comment by solarkennedy** [comment]
> The syscall preemption messiness.

But is that fixed now in 1.16?

**Comment by sargun** [comment]
No, but we gotta eat it at some point. It looks like they've worked out most of the bugs. Early days of 1.16 were more problematic.

**Comment by solarkennedy** [comment]
@sargun I don't want you to have to rebase forever. 
Can you do `1.16.15` and rebase, and then lets do this?

**Comment by sargun** [comment]
This is ready to review.

**Review by MyUmmaGumma — APPROVED** [review]

**Comment by solarkennedy** [comment]
Let's do it! (once the containerd thing is solved)

**Review by solarkennedy — APPROVED** [review]

**Pull request merged**
