### PR TITLE
Add error counters and latency measures for long-running tasks

### PR DESCRIPTION
**Pull request by hechaoli**
# Problem

For APIs, we have gRPC stats provided by [opencensus](https://github.com/danielkhan/openconsensus/tree/master/schemas/opencensus). However, no stats/metrics exist for long-running tasks in VPC Service. 

# Fix
This PR adds an error counter and a latency measure for all long-running tasks. With this change, we ensure that for each failed execution, we count the error whereas for each successful execution, we measure its latency. Alerts will be set up based for these two metrics so that we will catch it early when certain tasks keep failing or have an increased execution time.

### CODE REVIEW

**Review by MyUmmaGumma — APPROVED** [review]
Super!

**Review by aloktiagi — COMMENTED** [review]
changes look good. Trying to understand the motivation, are we looking to get better insights into AWS API call latencies or will these be useful in debugging issues.

Additionally do you see if these can be actionable in some sense? Like open an AWS ticket?

**Comment by hechaoli** [comment]
> changes look good. Trying to understand the motivation, are we looking to get better insights into AWS API call latencies or will these be useful in debugging issues.

Not only AWS API latency but the overall monitoring of long-running tasks is missing. We don't know which ones fail when or how long does each task takes in general. Had we had the monitoring in place, we should have caught the state-size incident earlier before it was manifested as a state-size increase.

> Additionally do you see if these can be actionable in some sense? Like open an AWS ticket?
I will create alerts for long-running task errors and latencies. Debugging will be needed when they are fired. As of the next step action, it could be AWS ticket if it's proven to be AWS issue or fixing bugs in VPC service itself.

**Comment by aloktiagi** [comment]
> Not only AWS API latency but the overall monitoring of long-running tasks is missing. We don't know which ones fail when or how long does each task takes in general. Had we had the monitoring in place, we should have caught the state-size incident earlier before it was manifested as a state-size increase.

I remember most of the tasks setting a context deadline. If a task's time to finish is equal to the context deadline, maybe we wont see an uptick in metrics? Or are you also measuring the number of times we hit the context deadline expiry?

**Comment by hechaoli** [comment]
> I remember most of the tasks setting a context deadline. If a task's time to finish is equal to the context deadline, maybe we wont see an uptick in metrics? Or are you also measuring the number of times we hit the context deadline expiry?

There are 3 cases:
* The task finishes within the deadline. Then each successful execution will record a latency. We'll have an alert on the latency with a reasonable threshold based on historical data. Say, if a task usually takes 100ms to finish but suddenly it takes 1 seconds, then we should debug why.
* The task doesn't finish within the deadline, then an error counter will be increased. If it reaches a threshold, then an alert will be triggered and we should debug why it fails to finish within the deadline.
* The task doesn't time out but also doesn't finish successfully. Again, an error counter will be increased and we should debug why the failure rate increases.

**Comment by aloktiagi** [comment]
> > I remember most of the tasks setting a context deadline. If a task's time to finish is equal to the context deadline, maybe we wont see an uptick in metrics? Or are you also measuring the number of times we hit the context deadline expiry?
> 
> There are 3 cases:
> 
> * The task finishes within the deadline. Then each successful execution will record a latency. We'll have an alert on the latency with a reasonable threshold based on historical data. Say, if a task usually takes 100ms to finish but suddenly it takes 1 seconds, then we should debug why.
> * The task doesn't finish within the deadline, then an error counter will be increased. If it reaches a threshold, then an alert will be triggered and we should debug why it fails to finish within the deadline.
> * The task doesn't time out but also doesn't finish successfully. Again, an error counter will be increased and we should debug why the failure rate increases.

Cool. Determining the threshold based on historical data has been a challenge in the past for me in other areas. But maybe the data might not be too noisy here. We can tune as we move along. I am sure you are planning to document these.

**Review by aloktiagi — APPROVED** [review]

**Comment by hechaoli** [comment]
> Cool. Determining the threshold based on historical data has been a challenge in the past for me in other areas. But maybe the data might not be too noisy here. We can tune as we move along. I am sure you are planning to document these.

I'll update the runbook once the change is rolled out.

**Pull request merged**
