### PR TITLE
CNI Plugin [WIP]

### PR DESCRIPTION
**Pull request by sargun**
Add CNI Plugin

### CODE REVIEW

**Comment by sargun** [comment]
There's a bunch of TODOs here. And there's no background GC process, but it's a start in the right direction, IMHO.

If you want to try it out, drop a file in `/etc/cni/net.d/10-sargun.conf` (make sure there's no lower files)

with the contents:
```
{
  "cniVersion": "0.3.0",
  "type": "titus",
  "name": "sargun",
  "KubeletAPIURL": "https://localhost:10250/pods"
}
```

(I have absolutely no idea what the name does)

**Comment by sargun** [comment]
@hankjacobs @rgulewich I'm also thinking of splitting out the bits under vpc/service/ into a separate PR. What do you think?

**Comment by sargun** [comment]
Also, I'm sorry. This wasn't supposed to be 1000 lines. I have no idea how it became 1 thousand lines. :(.

**Comment by hankjacobs** [comment]
+1 on splitting the vpc/service stuff into a separate PR. Will make it easier to review

**Comment by sargun** [comment]
@hankjacobs Already split: https://github.com/Netflix/titus-executor/pull/362

**Pull request merged**
