### PR TITLE
Always make TSA handle perf syscalls

### PR DESCRIPTION
**Pull request by solarkennedy**
This changes makes it so *whenever* TSA is enabled for net, it also
grants perf syscalls too "for free". This is an incremental step towards
enabling perf syscalls on all titus containers.

This is only part1. Part2 will come in a differnet PR unifying the
seccomp profiles.

### CODE REVIEW

**Comment by solarkennedy** [comment]
@aloktiagi do you have opinions on this? Your new traffic steering will also adjust how this goes

**Review by MyUmmaGumma — COMMENTED** [review]
I think we should retain different identities for perf and net syscall interception
1. These are still in flux.
2. We might want to separate out individual perf and net calls also for different system behavior.

**Comment by aloktiagi** [comment]
> 

@MyUmmaGumma when enabling ioctl + network syscall interception, doesn't that create a deadlock or was it only sendmsg?

**Comment by solarkennedy** [comment]
> > 
> 
> @MyUmmaGumma when enabling ioctl + network syscall interception, doesn't that create a deadlock or was it only sendmsg?

Oh crap, do we both try to intercept ioctl?
On the perf one we only intercept 2 particular ioctls (if that makes a difference)

**Review by sargun — APPROVED** [review]

**Comment by solarkennedy** [comment]
@MyUmmaGumma / @aloktiagi can you confirm: is it ok for me to add the perf (includes ioctl intercept) filter for network interception too?

**Comment by solarkennedy** [comment]
I still want this in place. My ultimate goal here is to enable `perf` on all tasks, without opting in.

To do this, it means TSA needs to use the perf filter all the time.

**Comment by solarkennedy** [comment]
Closing this as we are archiving this repository.

**Pull request closed without merging**
