### PR TITLE
Add hedging to AWS requests

### PR DESCRIPTION
**Pull request by sargun**

### CODE REVIEW

**Comment by rgulewich** [comment]
This looks more like retry logic with a backoff to me - is there no retry logic in the AWS client that we can use?

**Comment by sargun** [comment]
@rgulewich It's hedging + retry logic kind of. Basically, the second, and third requests wont start except for some period after the first started. We already have retries. Retries work slightly differently, in that they happen after a call has failed. The AWS client already has backoff + retries.

**Comment by sargun** [comment]
@rgulewich updated.

**Comment by rgulewich** [comment]
@sargun Great - thanks for the detailed comment.  I probably won't be the last person with questions... :)

**Pull request merged**
