### PR TITLE
optimization debian package manager tweaks

### PR DESCRIPTION
**Pull request by Rajpratik71**
By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages .

By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.

This results in smaller downloads and installation of packages .

Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .

Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

### Description of the Change

**FIXME**: please add at least one sentence explaining why changes here are being made.

### CODE REVIEW

**Comment by sargun** [comment]
Please don't make modifications directly to files under vendor/

**Comment by sargun** [comment]
Please don't make modifications directly to files under vendor/

**Comment by Rajpratik71** [comment]
> Please don't make modifications directly to files under vendor/

done as requested

**Comment by solarkennedy** [comment]
It looks like the tini submodule hash changed. @Rajpratik71 is that expected?

**Comment by Rajpratik71** [comment]
@solarkennedy  closing this one and created a fresh pull at #443

**Pull request closed without merging**
