### PR TITLE
Netflix runc version to support hybrid cgroup hierarchy

### PR DESCRIPTION
**Pull request by aloktiagi**
Netflix runc version to support hybrid cgroup hierarchy

### CODE REVIEW

**Comment by solarkennedy** [comment]
With this in place, GPU tasks won't get cgroup v2, will that be a problem?

**Comment by solarkennedy** [comment]
I don't know what it will take to get this to work in integration tests.
I think you will have to install the alt runtime in the Dockerfile for the tests?

**Comment by sargun** [comment]
Yeah, I think we should install the runc-alt for the integration tests to make sure out mix and match works.

**Comment by aloktiagi** [comment]
Would this require an update to the titusoss/titus-agent image?

**Comment by aloktiagi** [comment]
Ok. The last commit made it work.

**Comment by aloktiagi** [comment]
@sargun @solarkennedy how do you feel about this? ok to go ahead?

**Comment by solarkennedy** [comment]
Can you rebase onto a single commit?

I'm going to be OOO for the next week, so if you want to push it needs to be in coordination with @sargun . 
Also the upgrade of titus-executor needs to be with the same commit as a change to titus-agent to include the equivalent change to the docker daemon.json and nflx-runc package.

**Review by sargun — APPROVED** [review]

**Comment by aloktiagi** [comment]
> Can you rebase onto a single commit?
> 
> I'm going to be OOO for the next week, so if you want to push it needs to be in coordination with @sargun . Also the upgrade of titus-executor needs to be with the same commit as a change to titus-agent to include the equivalent change to the docker daemon.json and nflx-runc package.

Sounds good. Will update the titus-agent PR with the required titus-executor version.

**Comment by sargun** [comment]
I don't think we will need this anymore.

**Comment by aloktiagi** [comment]
> I don't think we will need this anymore.

Correct! closing.

**Pull request closed without merging**
