### PR TITLE
Add labels describing resource allocation to containers

### PR DESCRIPTION
**Pull request by gabrielhartmann**
Docker container creation events don't contain information about resources.  In order to avoid a second call to inspect a container after construction we put this information in _small_ labels on the container here.

```bash
$ docker run --rm --label com.netflix.titus.cpu=1 --cpu-shares 100 ubuntu:latest ls
...
```

```bash
$ docker events --format "{{json .}}" | jq .
{
  "status": "create",
  "id": "d15607d8bb28b8a8038cc80b49ef65e22b1669c25e3af07131be4e60595320e9",
  "from": "ubuntu:latest",
  "Type": "container",
  "Action": "create",
  "Actor": {
    "ID": "d15607d8bb28b8a8038cc80b49ef65e22b1669c25e3af07131be4e60595320e9",
    "Attributes": {
      "com.netflix.titus.cpu": "1",
      "image": "ubuntu:latest",
      "name": "gifted_vaughan"
    }
  },
  "scope": "local",
  "time": 1539819620,
  "timeNano": 1539819620158171600
}
...
```

### CODE REVIEW

**Comment by sargun** [comment]
Does it make sense to add an integration test?

**Comment by gabrielhartmann** [comment]
@sargun I did a quick search for tests when I was writing this but didn't see any tests checking for label correctness.  Do you have a pointer?

**Comment by rgulewich** [comment]
@gabrielhartmann @sargun What about just adding a unit test for `NewContainer()` to `executor/runtime/container_test.go`?

**Comment by sargun** [comment]
@rgulewich :+1:

**Comment by gabrielhartmann** [comment]
@sargun @rgulewich: I added a unit test.  I also added a field for workload type.  Please have a second look.

**Pull request merged**
