### PR TITLE
Use modern busybox instead of alpine because pgrep works

### PR DESCRIPTION
**Pull request by solarkennedy**
cherry-picking a fix to reduce the diff in my other PR.

----

I'm banging my head on why tests fail on buildkite but not on my laptop.

I want to make sure this change has nothing to do with it.

### CODE REVIEW

**Comment by solarkennedy** [comment]
> I suppose you don't plan to merge this, since branch builds should give you the information you need?

I was going to go and merge if it is green, yes.

**Comment by solarkennedy** [comment]
Well, I didn't expect this to fail, but it did. I think it is just revealing an underlying bug or difference between buildkite and my laptop (where it passes).

Here I see 
```
Jun 10 21:11:37 41339826f554 89ad544d5134[46]: [FATAL tini (26)] Failed to open stdout redirect path: No such file or directory
```

And:
```
time=2021-06-10T21:11:36Z level=info msg=no mainContainerRoot available, volumes will not be sharable between containers taskID=Titus-90130-TestBasicMultiContainer-0-2
```

Which indicates two bugs I can fix:
1. We have overlay2 on in these buildkite nodes.... eh but still docker-in-docker, I guess that still wont work :(
2. Tini should only redirect logs if we do have the /logs shared volume available (which I guess we won't with docker-in-docker). I didn't realize that was a fatal error for tini.

**Comment by alekar** [comment]
Can we mirror the image in titusoss before we use it in tests?

**Review by alekar — APPROVED** [review]

**Comment by solarkennedy** [comment]
> Can we mirror the image in titusoss before we use it in tests?

Can do

**Pull request merged**
